name: Print Secret (Manually Triggered)

on:
  workflow_dispatch:

jobs:
  print-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Show a masked secret
        run: |
          echo "The secret is: ${{ secrets.MOBSF_API_KEY }}"
